[PR] 🔀 4주차 #20 정리
Nelmm/DesignPattern pull request #26
Opened 2021-12-16 00:41 UTC by ventulus95

closed #20

2021-12-16 03:44 UTC, gowoonsori commented on 구조/4주차-브릿지/chang.md
> +실제로  내부에 로그 라이브러리만 갈아 끼우면 된다. (log4j2, log4j, logback와 같이 내부를 갈아 끼우면 되는 방식.)
@Slf4j 어노테이션을 사용하면 컴파일타임에 Logger log = LoggerFactory.getLogger(...) 을 삽입해준다는 내용 좋았습니다.

2021-12-16 04:04 UTC, jun108059 approved these changes

2021-12-16 04:04 UTC, jun108059 commented on 구조/4주차-브릿지/chang.md
> +→ 이런식으로 Slf4J를 가장 먼저 두면서 ⇒ 다른 log 라이브러리를 사용하면,  사용성은 유지하되, 다른 새로운 라이브러리로 대체 가능하게 만들 수 있다.
@Slf4J 에너테이션이 AOP로 동작하는 줄 알았는데, 컴파일 할 때 Logger 객체를 만들어주는건 처음 알았네요..! 감사합니다~ 👍👍

![Slf4j](https://user-images.githubusercontent.com/42997924/146306097-b00be801-4185-4dea-9a26-93f270d23181.png)

2021-12-16 08:34 UTC, gowoonsori approved these changes

2021-12-16 23:21 UTC, dev-splin requested changes
전체적으로 이미지가 안 나오네요..!!!
확인 부탁드립니다 😢

2021-12-16 23:21 UTC, dev-splin commented on 구조/4주차-브릿지/chang.md
> +하나의 계층 구조일때보다 각기 나누었을때 독립적인 게층 구조로 발전 시킬 수 있다.
오타 있습니다!

2021-12-17 04:26 UTC, gowoonsori commented on 구조/4주차-브릿지/chang.md
> +하나의 계층 구조일때보다 각기 나누었을때 독립적인 게층 구조로 발전 시킬 수 있다.
> 전체적으로 이미지가 안 나오네요..!!! 확인 부탁드립니다 😢

제가 대신 수정해서 push했습니당.

2021-12-17 06:25 UTC, ventulus95 commented on 구조/4주차-브릿지/chang.md
> +하나의 계층 구조일때보다 각기 나누었을때 독립적인 게층 구조로 발전 시킬 수 있다.
흠... 이미지 상위까지 올라가야지 노출되는거죠? 
`image/1.png` 이렇게는 안되는건가요? ㅠ 전체 경로 다적기 너무 귀찮은데 ㅋㅋ;

2021-12-17 14:56 UTC, jun108059 approved these changes

2021-12-17 14:56 UTC, jun108059 commented on 구조/4주차-브릿지/chang.md
> +하나의 계층 구조일때보다 각기 나누었을때 독립적인 게층 구조로 발전 시킬 수 있다.
PR 머지하면 현재 폴더부터 인식해서 보이긴할텐데, PR에서는 현재 폴더 경로를 인식하지 못해서 그런 것 같네요ㅠㅠ

Github에 이미지 올리는 꿀팁 관련해서 차주에 공유드릴게요! :D

2021-12-18 03:33 UTC, CJW23 approved these changes

2021-12-18 14:58 UTC, dev-splin commented on 구조/4주차-브릿지/chang.md
> +하나의 계층 구조일때보다 각기 나누었을때 독립적인 게층 구조로 발전 시킬 수 있다.
아 그래서 다른 분들은 이미지랑 같이 올리시는 거군요..!!
저는 이슈에 등록한 후 복붙하는데...

2021-12-18 14:58 UTC, dev-splin approved these changes

2021-12-19 13:16 UTC, merged